name: Deploy P001

on:
  push:
    branches:
      - master
    tags:
      - v*

      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Config
      run: cat Config.txt
      
    - name: Display New Config
      run: cat NewConfig.txt
  
